### ISSUE TITLE
1965和1966行单词中文释义错位

### ISSUE THREAD

**Issue by yqwen** [liurui39660/3000#2]
3000.xls中1965和1966两行的中文似乎反了

原文：
1965 rash 使稀薄
1966 rarefy 草率的，仓促的

**Comment by liurui39660** [comment]
Hi yqwen,

抱歉没有及时回复。

已经确认到该问题，问题出在原作者提供的Excel版上，我近期会试着再找一个可靠的Excel源把中文释义都替换掉。

P.S. 记得微臣有在百度网盘放过一个Excel版，改日我找一找。

**Comment by liurui39660** [comment]
Hi @yqwen,

抱歉没有及时回复

问题已经确认，出在原作者提供的Excel上

我近期找找其他合适的源，将中文部分替换掉

P.S. 记得微臣教育在百度网盘里放了一份，我改日找找

**Comment by liurui39660** [comment]
已经使用新的源将中文和英文的顺序都替换掉了。

新的源中1965为rarefy，1966为rash，二者对应的音标也已经调整了顺序。

中文和英文是同步修改的，应该不会再出现差错，但是音标的顺序暂时没有全部更新。

**Comment by yqwen** [comment]
辛苦了！感谢整理资料！受益匪浅~
