### ISSUE TITLE
polymath出现了两次

### ISSUE THREAD

**Issue by Julymycin** [liurui39660/3000#3]
line1718以及line1800

**Comment by liurui39660** [comment]
非常感谢指出错误，我稍后对照原版的检查一下是哪里的问题

如果你手上有3000书的话能否帮忙确认一下书中是否也出现了两次？

**Comment by Julymycin** [comment]
书中没有，应该是少了该list中的poignant这个单词。

**Comment by liurui39660** [comment]
嗯嗯，不知能否再帮忙一下把书上poignant单词的那里拍照一下，我稍后对照着手动修改一下，我手边现在没有3000的纸本书

**Comment by Julymycin** [comment]
![image](https://user-images.githubusercontent.com/24741969/64020561-82045180-cb64-11e9-8986-d471e552739d.png)
poignant出现在list 18 unit 9，polymath的话1718行那个是正确位置。

**Comment by liurui39660** [comment]
非常感谢你的帮助，我会尽快进行修正
