### ISSUE TITLE
1786 行的条件格式好像有问题, 请问怎么调整呢

### ISSUE THREAD

**Issue by flyingHuaJi** [liurui39660/3000#7]
<img width="1903" alt="image" src="https://user-images.githubusercontent.com/37231912/179021409-880415e3-79f1-4d68-b63a-3bf9448c5ff4.png">

**Comment by liurui39660** [comment]
的确存在问题，我已经重新应用了条件格式，现在三个版本的都正确了。
你可以下载新的版本，然后将旧版的'?'列复制到新版，以完成升级。
